[package]
name = "elf-maps"
version = "0.1.0"
authors = ["r4xjs <r4xjs@lowsec.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
elf = "0.0.10"
